services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/config/.env
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client-ng
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./client-ng:/app
      - /app/node_modules
    depends_on:
      - server
