export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = "INTERNAL_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  INVALID_ID = "INVALID_ID",

  // Auth
  AUTH_REQUIRED = "AUTH_REQUIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ACCESS_DENIED_ADMIN = "ACCESS_DENIED_ADMIN",
  ACCESS_DENIED_HOTLINE = "ACCESS_DENIED_HOTLINE",
  ACCESS_DENIED_MONTEUR = "ACCESS_DENIED_MONTEUR",
  ACCESS_DENIED_SUPERADMIN = "ACCESS_DENIED_SUPERADMIN",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  // User
  INVALID_ROLE = "INVALID_ROLE",
  ROLES_UPDATED = "ROLES_UPDATED",

  // Camera
  CAMERA_NOT_FOUND = "CAMERA_NOT_FOUND",
  CAMERA_ERROR = "CAMERA_ERROR",
  CAMERA_UNREACHABLE = "CAMERA_UNREACHABLE",

  // Client file
  CLIENT_FILE_NOT_FOUND = "CLIENT_FILE_NOT_FOUND",
  CLIENT_FILE_DUPLICATE_SIRET = "CLIENT_FILE_DUPLICATE_SIRET",
  CLIENT_FILE_DUPLICATE_NAME = "CLIENT_FILE_DUPLICATE_NAME",
  CLIENT_FILE_CREATE_ERROR = "CLIENT_FILE_CREATE_ERROR",
  CLIENT_FILE_UPDATE_ERROR = "CLIENT_FILE_UPDATE_ERROR",
  CLIENT_FILE_DELETED = "CLIENT_FILE_DELETED",
  NO_FILE_PROVIDED = "NO_FILE_PROVIDED",
  CLIENT_FILE_UPLOAD_ERROR = "CLIENT_FILE_UPLOAD_ERROR",
  DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND",
  DOCUMENT_DELETE_ERROR = "DOCUMENT_DELETE_ERROR",

  // Contacts
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",
  CONTACT_CREATE_ERROR = "CONTACT_CREATE_ERROR",

  // Shared "deleted" success
  DELETED = "DELETED",

  // Intervention reports
  REPORT_NOT_FOUND = "REPORT_NOT_FOUND",
  REPORT_CREATE_ERROR = "REPORT_CREATE_ERROR",
  REPORT_UPDATE_ERROR = "REPORT_UPDATE_ERROR",
  REPORT_DELETED = "REPORT_DELETED",

  // Items
  ITEM_NOT_FOUND = "ITEM_NOT_FOUND",
  INVALID_PREPARATION = "INVALID_PREPARATION",
  INVALID_OPERATION = "INVALID_OPERATION",
  ITEMS_UPDATED = "ITEMS_UPDATED",

  // Reminders
  NO_REMINDERS_DUE = "NO_REMINDERS_DUE",
  REMINDERS_SENT = "REMINDERS_SENT",
  REMINDER_SEND_ERROR = "REMINDER_SEND_ERROR",

  // Shipments
  SHIPMENT_NOT_FOUND = "SHIPMENT_NOT_FOUND",
  SHIPMENT_MISSING_FIELDS = "SHIPMENT_MISSING_FIELDS",
  SHIPMENT_DELETED = "SHIPMENT_DELETED",
  NO_SHIPMENTS_TO_ARCHIVE = "NO_SHIPMENTS_TO_ARCHIVE",
  ARCHIVE_NOT_FOUND = "ARCHIVE_NOT_FOUND",
  ARCHIVE_XLSX_UNAVAILABLE = "ARCHIVE_XLSX_UNAVAILABLE",

  // Vehicles
  VEHICLE_FETCH_ERROR = "VEHICLE_FETCH_ERROR",
  VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND",
  VEHICLE_MISSING_FIELDS = "VEHICLE_MISSING_FIELDS",
  VEHICLE_LICENSE_PLATE_DUPLICATE = "VEHICLE_LICENSE_PLATE_DUPLICATE",
  VEHICLE_INVALID_MERCEDES_MODEL = "VEHICLE_INVALID_MERCEDES_MODEL",
  VEHICLE_INVALID_NISSAN_MODEL = "VEHICLE_INVALID_NISSAN_MODEL",
  VEHICLE_ASSIGNED_USER_NOT_FOUND = "VEHICLE_ASSIGNED_USER_NOT_FOUND",
  VEHICLE_CREATE_ERROR = "VEHICLE_CREATE_ERROR",
  VEHICLE_UPDATE_ERROR = "VEHICLE_UPDATE_ERROR",
  VEHICLE_DELETED = "VEHICLE_DELETED",
  VEHICLE_DELETE_ERROR = "VEHICLE_DELETE_ERROR",
  VEHICLE_SEARCH_ERROR = "VEHICLE_SEARCH_ERROR",
  VEHICLE_DOC_MISSING_FIELDS = "VEHICLE_DOC_MISSING_FIELDS",
  VEHICLE_DOC_UPLOAD_ERROR = "VEHICLE_DOC_UPLOAD_ERROR",
  VEHICLE_DOC_DELETE_ERROR = "VEHICLE_DOC_DELETE_ERROR",
}
